### PR TITLE
fix tests and support application/binary

### LINKED ISSUE #12: An option to return binary as is in fetch requests

### LINKED ISSUE #13: Add tests

### LINKED ISSUE #22: Add an option to connect to Kafka using TLS

### LINKED ISSUE #23: Add an option to use SASL/PLAIN authentication with Kafka

### PR DESCRIPTION
**Pull request by id**
fixes #12
fixes #13
fixes #22
fixes #23

### CODE REVIEW

File: lib/kastlex.ex [hunk 1]
```diff
@@ -3,91 +3,89 @@ defmodule Kastlex do
...
     cg_cache_dir = system_env("KASTLEX_CG_CACHE_DIR", :priv)
     Logger.info "Consumer groups cache directory: #{cg_cache_dir}"
+    Application.put_env(:kastlex, :cg_cache_dir, cg_cache_dir)
     cg_exclude_regex = system_env("KASTLEX_CG_EXCLUDE_REGEX", nil)
     maybe_log_parameter("Consumer groups exclude regexp", cg_exclude_regex)
-
-    Application.put_env(:kastlex, :permissions_file_path, permissions_file_path)
-    Application.put_env(:kastlex, :passwd_file_path, passwd_file_path)
-    Application.put_env(:kastlex, :cg_cache_dir, cg_cache_dir)
     Application.put_env(:kastlex, :cg_exclude_regex, cg_exclude_regex)
```
Comment (zmstone) [inline lib/kastlex.ex]: for easier multi-pattern support. we can perhaps put exclude patterns to a file ?

File: lib/kastlex/metadata_cache.ex [hunk 2]
```diff
@@ -28,6 +28,15 @@ defmodule Kastlex.MetadataCache do
     {:ok, brokers}
   end
 
+  def existing_topic?(t, p) do
```
Comment (zmstone) [inline lib/kastlex/metadata_cache.ex]: `existing_partition?` ?

Comment (zmstone) [inline lib/kastlex/metadata_cache.ex]: and this function is not used ?

Comment (id) [inline lib/kastlex/metadata_cache.ex]: no, I created it first for message_controller but then found an easier way to verify if a given topic/partition is valid (via brod_client's cache). But then decided to leave this function as is.

Yes, `existing_partition` is probably a better name.

File: lib/kastlex.ex (hunk 1 above)
Comment (id) [inline lib/kastlex.ex]: Create a separate issue?

File: web/controllers/api/v1/message_controller.ex [hunk 3]
```diff
@@ -116,16 +115,72 @@ defmodule Kastlex.API.V1.MessageController do
...
-                     highWmOffset: highWmOffset,
+            do_fetch(sock_pid, req_fun, size, offset, type)
+          messages when type == "json" ->
+            resp = %{highWmOffset: highWmOffset,
                      size: size,
                      messages: messages_to_map(messages)
                     }
             {:ok, resp}
+          messages when type == "binary" ->
+            {:kafka_message, _offset, _magic_byte, _attributes, _key, value, _crc} = hd(messages)
```
Comment (zmstone) [inline web/controllers/api/v1/message_controller.ex]: can we make use of the record ?
soon we'll add another field `timestamp` to the message, then this will crash

File: README.md [hunk 4]
```diff
@@ -16,12 +16,21 @@ By default KastleX will try to connect to kafka at localhost:9092 and to zookeep
...
+`auto.create.topics.enable` parameter in Kafka's server.properties set
+to `false`.
+
 # API
 
 ## Produce messages
 
     POST /api/v1/messages/:topic
-    POST /api/v1/messages/:topic/:partition
+    POST /api/v1/messages/:topic?partition=xx
```
Comment (zmstone) [inline README.md]: revert API ?

File: config/config.exs [hunk 5]
```diff
@@ -33,6 +33,14 @@ config :phoenix, :generators,
   migration: true,
   binary_id: false
 
+config :mime, :types, %{
+  "*/*" => ["json"],
+  "application/json" => ["json"],
+  "application/binary" => ["binary"],
+  "application/avro.binary" => ["avro"],
```
Comment (zmstone) [inline config/config.exs]: what are these two for ?

Comment (id) [inline config/config.exs]: you mean, why do we need to handle binary and avro.binary content types in client requests?

Comment (zmstone) [inline config/config.exs]: yes

Comment (id) [inline config/config.exs]: binary: when client specifies "Accept: application/binary" header, KastleX will return value of the message at the given offset in response body and will not try to format it in json.

avro.binary: for the future, the idea is to decode messages in KastleX and return them as json (the better name probably would be "decoded-avro-binary" or something like this).

Comment (zmstone) [inline config/config.exs]: If it's for the future, we add it in the future.
Having them now will lead to confusion.

And when it's avro.binary, there is no way for kastlex to know the schema ID.
when it's confluent.avro.binary, we need to have the schema registry URL in config or ?

Comment (id) [inline config/config.exs]: yes, these must be supplied in request parameters

Comment (id) [inline config/config.exs]: ok, removing avro
